config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'items#index'
  resources :items do
    resources :orders
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  attr_accessor :token, :price_id


  PRICE_REGEX = /\A[0-9]+\z/
  validates :token, presence: true
  validates :price, presence: true
  validates :comment, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 300 }
  validates :price, numericality: { less_than_or_equal_to: 9999999 },format: { with: PRICE_REGEX }

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    if user_signed_in?
      @order = Order.new
      @item = Item.find(params[:item_id])
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @order = Order.new(order_params)
    price_id = params[:price_id]
    @order.price = price_id
    if @order.valid?
      pay_item
      @order.save
      item_count
      return redirect_to root_path
    else
      render :new
    end
  end

  private

  def order_params
    @item = Item.find(params[:item_id])
    params.require(:order).permit(:price, :comment).merge(user_id: current_user.id, item_id: @item.id, token: params[:token], price_id: params[:price_id])

  end

  def pay_item
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      amount: @order.price,
      card: order_params[:token], 
      currency: 'jpy' 
    )
  end

  def item_count
    @item = Item.find(params[:item_id])
    @item.start_amount = @item.start_amount + @order.price
    @item.person_num += 1
    @item.save
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/new.html.erb
<%= render "items/header" %>

<div class='order-new-page'>
  <h1 class='order-new-title'>リターンを選択し、必要情報を入力してください</h1>
  <div class='order-new-container'>
    <div class='order-new-main'>
      <%= form_with model: @order, url: item_orders_path, id: 'charge-form', class: 'card-form', local: true do |form| %>
      <%= render 'devise/shared/error_messages', model: form.object %>
        <div class='price-box'>
          <ul>
            <%= label_tag :check[0] do %>
              <li class='price-box-list'>
                <div class='price-list'>
                  <div class='price-content'>
                    <div class="price-check-box">
                      <%= check_box_tag :check[0], id:'price-check' %>
                      <%= label_tag :check[0], '500円', class:'price-check' %>
                    </div>
                    <div class='price-description'>
                      お礼メッセージ
                      ご支援いただいた方に、心からのお礼をお送りさせていただきます。
                      ※支援時、必ず備考欄にご希望のお名前をご記入ください。
                    </div>
                    <div class="price-detail">
                      <div class="price-support-person"><i class="fas fa-user"></i>支援者：<%= @item.person_num %>人</div>
                      <div class="send-plan"><i class="fa fa-truck"></i>お届け予定：2021年01月</div>
                    </div>
                  </div>
                  <div class='price-image-box'>
                    <%= image_tag "cat-1941089_1280.jpg", class: 'price-image' %>
                  </div>
                </div>
              </li>
            <% end %>

            <%= label_tag :check[1] do %>
              <li class='price-box-list'>
                <div class='price-list'>
                  <div class='price-content'>
                    <div class="price-check-box">
                      <%= check_box_tag :check[1], id:'price-check' %>
                      <%= label_tag :check[1], '8000円', class:'price-check' %>
                    </div>
                    <div class='price-description'>
                      お礼メッセージ
                      ご支援いただいた方に、心からのお礼をお送りさせていただきます。
                      ※支援時、必ず備考欄にご希望のお名前をご記入ください。
                    </div>
                    <div class="price-detail">
                      <div class="price-support-person"><i class="fas fa-user"></i>支援者：<%= @item.person_num %>人</div>
                      <div class="send-plan"><i class="fa fa-truck"></i>お届け予定：2021年01月</div>
                    </div>
                  </div>
                  <div class='price-image-box'>
                    <%= image_tag "cat-1941089_1280.jpg", class: 'price-image' %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>

        <div class='order-new-form'>
          <h2>支援金額</h2>
          <div class='order-price'>
            <div class="price-total">
              <h2>合計 <span id='price-sum'></span>円</h2>
            </div>
            <div class="price-addition">
              <%= form.label '金額上乗せ支援', class:'price-addition-check' %>
              <%= form.text_field :price, id:'item-price' %>
            </div>
          </div>
          <h2>クレジットカード情報入力</h2>
          <div class="card-container">
            
            <div class='card-information'>
              <div class='card-number'>
                <p>クレジットカード番号</p>
                <%= form.text_field :number, class:"numbers", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
                <div class="available-card">
                  <%= image_tag "card-mastercard.gif", class: 'card-image'%>
                  <%= image_tag "card-visa.gif", class: 'card-image'%>
                  <%= image_tag "card-jcb.gif", class: 'card-image'%>
                  <%= image_tag "card-amex.gif", class: 'card-image'%>
                </div>
              </div>
              <div class='card-cvc'>
                <p>セキュリティコード</p>
                <%= form.text_field :cvc, class:"cvc", placeholder:"3桁の番号", maxlength:"4" %>
              </div>
              <div class='expiration-date'>
                <p>有効期限</p>
                <div class='expiration-date-name'>
                  <%= form.text_field :exp_month, class:"exp_month", placeholder:"月" %>
                  <%= form.text_field :exp_year, class:"exp_year", placeholder:"年" %>
                </div>          
              </div>
            </div>
          </div>
          <h2>応援コメント</h2>
          <div class='support-comment'>
            <%= form.text_area :comment, placeholder: "コメント", size:'85x5' %>          
          </div>
          <div class='order-btn'>
            <%= form.submit "支援する", class:"order-new-btn" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class='order-new-side'>
      <div class="order-project-container">
        <h2>支援者になるプロジェクト</h2>
        <div class='new-project-list'>
          <%= image_tag @item.image, class: 'new-project-image'%>
          <h1 class='new-project-name'><%= @item.title %></h1>
          <div class='new-project-tag'>
            <div class='project-tag-name'><i class="fas fa-tags"></i><%= @item.tag.name %></div>
            <div class='project-tag-name'><i class="fas fa-tags"></i>動物・植物</div>
          </div>
          <div class='new-project-detail'>
            <div class='new-project-amount'>現在<span><%= @item.start_amount %>円</span></div>
            <div class='new-project-support'>支援者<span><%= @item.person_num %>人</span></div>
            <div class='new-project-day'>残り<span><%= @item.remaining_days %>日</span></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "items/footer" %>