config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  root to: 'items#index'
  resources :items do
    resources :orders
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :orders, dependent: :destroy
  belongs_to :user
  has_rich_text :content

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :tag

  has_one_attached :image
  with_options presence: true do
    validates :image
    validates :title
    validates :sub_title
    validates :target_amount
    validates :day_id
    with_options numericality: { other_than: 0 } do
      validates :tag_id
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show, :destroy]

  
  def index 
    Item.find_each do |item|
      day_count = (item.day_id - Date.today).to_i
      item.update(remaining_days: day_count)
    end
    @items = Item.includes(:user)
  end

  def new
    if user_signed_in?
      @item = Item.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.valid?
      if @item.day_id < Date.today
        render :new
      end
      @item.start_amount = 0
      @item.person_num = 0
      @item.remaining_days = (@item.day_id - Date.today).to_i
      @item.save
      return redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      return redirect_to item_path(@item.id)
    else
      render :edit
    end
  end

  def show
    @users = User.all
    @orders = Order.order("created_at DESC")
    @item.remaining_days = (@item.day_id - Date.today).to_i
    @content_truncate = ApplicationController.helpers.strip_tags(@item.content.to_s).gsub(/[\n]/,"").strip.truncate(100)
    @achievement_rate = (@item.start_amount * 100) / @item.target_amount
  end

  def destroy
    if @item.destroy
      return redirect_to root_path
    else
      render :show
    end
  end

  def short_description
    description[0, 9] + '...'
  end

  private

  def item_params
    params.require(:item).permit(:image, :title, :sub_title, :content, :target_amount, :start_amount, :day_id, :remaining_days, :tag_id).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='cloud-details01'>
      <h2 class='footer-content-head'>プロジェクト掲載について</h2>
      <ul>
        <li class="footer-title">プロジェクトをはじめる</li>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='cloud-details02'>
      <h2 class='footer-content-head'>プロジェクトをさがす</h2>
      <ul>
        <li class="footer-title">カテゴリからさがす</li>
        <li><%= link_to 'テクノロジー・ガジェット', "#", class: "footer-link" %></li>
        <li><%= link_to 'プロダクト', "#", class: "footer-link" %></li>
        <li><%= link_to 'フード・飲食店', "#", class: "footer-link" %></li>
        <li><%= link_to 'アニメ・漫画', "#", class: "footer-link" %></li>
        <li><%= link_to '音楽', "#", class: "footer-link" %></li>
        <li><%= link_to '書籍・雑誌出版', "#", class: "footer-link" %></li>
        <li><%= link_to 'フード・飲食店', "#", class: "footer-link" %></li>
        <li><%= link_to 'ビューティーヘルスケア', "#", class: "footer-link" %></li>
        <li><%= link_to 'チャレンジ', "#", class: "footer-link" %></li>
        <li><%= link_to 'ファッション', "#", class: "footer-link" %></li>

      </ul>
    </div>
    <div class='cloud-details03'>
      <h2 class='footer-content-head'>Crowdfunding について</h2>
      <ul>
        <li class="footer-title">クラウドファンディングとは</li>
        <li><%= link_to 'よくある質問', "#", class: "footer-link" %></li>
        <li><%= link_to 'お問い合わせ', "#", class: "footer-link" %></li>
        <li><%= link_to '利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="copyright-name">
      COPYRIGHT &#169;Crowdfunding  ALL RIGHTS RESERVED.
    </div>
  </div>
</div>

app/views/items/_header.html.erb
<div class='header-main'>
  <div class='header'>
    <div class='heading'>
     
      <%= link_to 'Crowdfunding', root_path, class: 'title' %>
    </div>
    <div class='navbar'>
      <ul class='nav-lists'>
        <li><%= link_to 'クラウドファンディングをはじめる', new_item_path, class: 'class' %></li>
        <li><a class="class" href="#">さがす</a></li>
        <% if user_signed_in? %>
          <li><%= "#{current_user.nickname}" %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'class' %></li>
        <% else %>
          <li><%= link_to 'ログイン',  new_user_session_path, class: 'class' %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: 'class' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/items/_main-column.html.erb
<div class='item-contents'>
  <div class='item-pickup'>
    <%= image_tag "cat-1941089_1280.jpg", class: 'item-image'%>
    <h2 class='pickup-project-name'>プロジェクト名</h2>
    <div class='projects'>
      <div class='project-amount'>現在<span>840,000円</span></div>
      <div class='project-support'>支援者<span>120人</span></div>
      <div class='project-day'>残り<span>10日</span></div>
    </div>
  </div>

  <ul class='item-lists'>
    <li class='list'>
      <%= image_tag "cat-1941089_1280.jpg", class: 'item-list-image'%>
      <h2 class='pickup-list-name'>listプロジェクト名</h2>
      <div class='projects-list'>
        <div class='project-list-amount'>現在<span>540,000円</span></div>
        <div class='project-list-support'>支援者<span>120人</span></div>
        <div class='project-list-day'>残り<span>12日</span></div>
    </div>
    </li>
    <li class='list'>
      <%= image_tag "chris-chow-BhwRQr08PcM-unsplash.jpg", class: 'item-list-image'%>
      <h2 class='pickup-list-name'>listプロジェクト名</h2>
      <div class='projects-list'>
        <div class='project-list-amount'>現在<span>250,000円</span></div>
        <div class='project-list-support'>支援者<span>90人</span></div>
        <div class='project-list-day'>残り<span>5日</span></div>
    </div>
    </li>
    <li class='list'>
      <%= image_tag "coffee-1281880_1280.jpg", class: 'item-list-image'%>
      <h2 class='pickup-list-name'>listプロジェクト名</h2>
      <div class='projects-list'>
        <div class='project-list-amount'>現在<span>800,000円</span></div>
        <div class='project-list-support'>支援者<span>5790人</span></div>
        <div class='project-list-day'>残り<span>15日</span></div>
      </div>
      </li>
    <li class='list'>
      <%= image_tag "morning-819362_1280.jpg", class: 'item-list-image'%>
      <h2 class='pickup-list-name'>listプロジェクト名</h2>
      <div class='projects-list'>
        <div class='project-list-amount'>現在<span>3,000,000円</span></div>
        <div class='project-list-support'>支援者<span>2790人</span></div>
        <div class='project-list-day'>残り<span>20日</span></div>
      </div>
    </li>
  </ul>
</div>

<div class='start-project'>
  <div class='find-text'>
    <h1>国内最大のクラウドファンディングで新しい挑戦を見つけよう</h1>
    <div class='btn-find'><a class="class" href="#">プロジェクトをさがす</a></div>
  </div>
</div>

app/views/items/_sub-column.html.erb
<div class='new-project-contents'>
  <h1 class='new-project-title'>新着プロジェクト</h1>
  <div class='new-project-view'>
    <ul class='new-project-lists'>
      <% @items.each do |item|%>
        <li class='new-project-list'>
          <%= link_to image_tag(item.image, class: 'new-project-image'), item_path(item.id) %>
          <h1 class='new-project-name'><%= item.title %></h1>
          <div class='new-project-tag'>
            <div class='project-tag-name'><i class="fas fa-tags"></i><%= item.tag.name %></div>
            <div class='project-tag-name'><i class="fas fa-tags"></i>動物・植物</div>
          </div>
          <div class='new-project-detail'>
            <div class='new-project-amount'>現在<span><%= item.start_amount %>円</span></div>
            <div class='new-project-support'>支援者<span><%= item.person_num %>人</span></div>
            <% if item.remaining_days > 0 %>
              <div class='new-project-day'>残り<span><%= item.remaining_days %>日</span></div>
            <% else %>
              <div class='new-project-day'><span>募集期間終了</span></div>
            <% end %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/items/edit.html.erb
<%= render "items/header" %>
<div class='new-page'>
  <div class="new-container">
  <h1 class='new-page-title'>プロジェクト編集</h1>
    <%= form_with(model: @item, local: true) do |form| %>
      <div class='overview-wrapper'>
        <div class="form-group">
          <div class='form-header'>
            <%= form.label :title, 'タイトル' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.text_field :title, placeholder: "あなただけのオリジナルタイトルを設定してください", class:"form-body-title"%>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :sub_title, '概要文' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.text_area :sub_title, placeholder: "３行程度で概要をまとめましょう", class:'form-body-subtitle'%>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :image, 'メイン画像' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.file_field :image, id:"item-image" %>
            <div class="choice_box">ドラック＆ドロップorクリック</div>
            <div id="image-list"></div>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :content, '本文' %>
            <span class="optional">任意</span>
          </div>
          <div class="form-body">
            <div class="form-body-line">
              <%= form.rich_text_area :content %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :tag_id, 'カテゴリ' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.collection_select(:tag_id, Tag.all, :id, :name, {}, {class:"tag-select"}) %>
          </div>
        </div>
      </div>
      <div class="item-btn">
        <%= form.submit "保存", class:'item-new-btn' %>
      </div>
      <% end %>
  </div>
</div>

<%= render "items/footer" %>

app/views/items/index.html.erb
<%= render "items/header" %>
<div class='main'>
  <div class='top-image'>
    <%= image_tag "walking-next-to-people-4435214_1280.png", class: 'header-image'%>
  </div>
  <div class='main-column'>
    <%= render "items/main-column", locals: { item: @item } %>
  </div>
   <div class='sub-column'>
    <%= render "items/sub-column" %>
  </div>
  <div class='work-report'>
    <div class='work-report-contents'>
      <h2 class='work-report-name'>最近の活動報告</h2>
      <ul class='work-report-box'>
        <li class='work-report-list'>
          <%= image_tag "cat-1941089_1280.jpg", class: 'work-report-image' %>
          <div class="btn-work-report">
            <i class="fas fa-bullhorn"></i>活動報告
          </div>
          <div class='work-report-title'>【10月5日】ウチのネコです。</div>
        </li>
        <li class='work-report-list'>
          <%= image_tag "cat-1941089_1280.jpg", class: 'work-report-image' %>
          <div class="btn-work-report">
            <i class="fas fa-bullhorn"></i>活動報告
          </div>

        </li>
        <li class='work-report-list'>
          <%= image_tag "cat-1941089_1280.jpg", class: 'work-report-image' %>
          <div class="btn-work-report">
            <i class="fas fa-bullhorn"></i>活動報告
          </div>
        </li>
      </ul>
    </div>
  </div>
  <%= image_tag "crowdfunding-3158320_1280.png", class: 'footer-image'%>
  
  <%= render "items/footer" %>
</div>

app/views/items/new.html.erb
<%= render "items/header" %>
<div class='new-page'>
  <div class="new-container">
  <h1 class='new-page-title'>プロジェクト編集</h1>
    <%= form_with(model: @item, local: true) do |form| %>
      <%= render 'devise/shared/error_messages', model: form.object %>
      <div class='overview-wrapper'>
        <div class="form-group">
          <div class='form-header'>
            <%= form.label :title, 'タイトル' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.text_field :title, placeholder: "あなただけのオリジナルタイトルを設定してください", class:"form-body-title"%>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :sub_title, '概要文' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.text_area :sub_title, placeholder: "３行程度で概要をまとめましょう", class:'form-body-subtitle'%>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :image, 'メイン画像' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.file_field :image, id:"item-image" %>
            <div class="choice_box">ドラック＆ドロップorクリック</div>
            <div id="image-list"></div>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :content, '本文' %>
            <span class="optional">任意</span>
          </div>
          <div class="form-body">
            <div class="form-body-line">
              <%= form.rich_text_area :content %>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="form-header">
            <%= form.label :target_amount, '目標金額' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.text_field :target_amount, placeholder: "目標金額", class:"form-body-amount" %>円
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :day_id, '募集終了日' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.date_field :day_id, class:"day-select", min: Date.current %>
          </div>
        </div>

        <div class="form-group">
          <div class="form-header">
            <%= form.label :tag_id, 'カテゴリ' %>
            <span class="indispensable">必須</span>
          </div>
          <div class="form-body">
            <%= form.collection_select(:tag_id, Tag.all, :id, :name, {}, {class:"tag-select"}) %>
          </div>
        </div>
      </div>
      <div class="item-btn">
        <%= form.submit "保存", class:'item-new-btn' %>
      </div>
      <% end %>
  </div>
</div>

<%= render "items/footer" %>

app/views/items/show.html.erb
<%= render "items/header" %>
<div class='show-top-page'>
  <h1 class='show-page-title'><%= @item.title %></h1>
  <ul class='show-tag'>
    <li class='show-tag-list'><i class="fas fa-tags"></i><%= @item.tag.name %></li>
    <li class='show-tag-list'><i class="fas fa-tags"></i>動物・植物</li>
  </ul>
  <div class='show-container'>

    <div class='main-container'>
      <%= image_tag @item.image, class: 'show-item-image' %>
      <div class='sub-title'><%= @item.sub_title %></div>
    </div>

    <div class='side-container'>
      <div class='side-item-contents'>
        <div class='total-inner'>
          <div class='backer-amount'>
            <h5><span>¥</span> 現在の支援総額</h5>
            <strong><%= @item.start_amount %>円</strong>
            <div>目標金額は<%= @item.target_amount %>円</div>
            <div class="achievement-rate">
              <div class="achievement" id="achievement" value="<%= @achievement_rate %>">
                <%= @achievement_rate %>％
              </div>
              <div class="achievement-bar" id="achievement-bar" >
              </div>
            </div>
          </div>
        </div>
        <div class='support-person'>
          <div class='support-person-number'><i class="fas fa-user"></i>支援者数</div>
          <div class='number'><%= @item.person_num %>人</div>
        </div>
        <div class='recruitment-end'>
          <div class='recruitment-end-number'><i class="far fa-clock"></i>募集終了まで残り</div>
          <% if @item.remaining_days > 0 %>
            <div class='number'><%= @item.remaining_days %>日</div>
          <% else %>
            <div class='number'>募集期間終了</div>
          <% end %>
        </div>

        <div class='support-box'>
          <div class='btn-support'>
            <% if user_signed_in? && current_user.id == @item.user_id %>
              <%= link_to 'プロジェクトを編集する', edit_item_path(@item.id), class: "support-name"%><i class="fa fa-chevron-circle-right"></i>
            <% elsif @item.remaining_days > 0 %>
              <%= link_to 'プロジェクトを支援する', new_item_order_path(@item.id), class: "support-name"%><i class="fa fa-chevron-circle-right"></i>
             <% else %>
              <%= link_to 'プロジェクトを支援する', "#", class: "support-name" %><i class="fa fa-chevron-circle-right"></i>
            <% end %>
          </div>
          <div class='btn-favorite'>
            <% if user_signed_in? && current_user.id == @item.user_id %>
              <%= link_to '削除', item_path(@item.id), method: :delete, class:'favorite' %>
            <% else %>  
              <div class='favorite'>お気に入り</div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<div class='show-content-page'>
  <div class='show-container'>

    <div class='main-content'>
      <ul class='tab-group'>
        <li class='tab tab-A is-active'>ホーム</li>
        <li class='tab tab-B'>活動報告</li>
        <li class='tab tab-C'>支援者</li>
        <li class='tab tab-D'>コメント</li>
      </ul>
      <div class="panel-group">
        <div class="panel tab-A is-show">
          <%= @item.content %>
        </div>
        <div class="panel tab-B">
          <ul class='works-report'>
            <%# <li class="works-report-list">
              まだ活動報告がありません。
            </li> %>
            <% 3.times do%>
              <li class="works-report-list">
                <h1 class='works-title'><%= @item.title %></h1>
                <div class="update-time">
                  <%= @item.updated_at.strftime("%Y-%m-%d %H:%M") %>
                </div>
                <%= @content_truncate %>
                <div class="next">
                  <%= link_to 'もっと見る', "#", class:'next-btn' %><i class="fa fa-angle-right"></i>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="panel tab-C">
          <%# 支援者リスト表示 %>
          <div class="message-container">
            <ul>
              <% @orders.each do |order| %>
                <% if order.item_id == @item.id %>
                <li class="message-list">
                  <div class="message-user-image">
                    <%= image_tag "Df9kcOEUcAAFsr9.jpg", class: 'profile-user-image' %>
                  </div>
                  <div class="message-box">
                    <div class="message-name-list">
                      <div class='message-nickname'>
                        <%= order.user.nickname %>
                      </div>
                      <div class="message-update-time">
                        <%= order.created_at.strftime("%Y-%m-%d %H:%M") %>
                      </div>
                    </div>
                    <div class="message-detail">
                      <%= order.comment %>
                    </div>
                  </div>
                </li>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="panel tab-D">
          <%= form_with(model: @item, local: true) do |form| %>
            <%= form.text_area "#", placeholder: "プロジェクトに対する意見や投稿しましょう。", class:'form-body-subtitle'%>
            <div class="message-btn">
              <%= form.submit "コメントする", class:'message-new-btn' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class='side-container'>
      <div class='profile-detail'>
        <div class='profile-box'>
          <%= image_tag "Df9kcOEUcAAFsr9.jpg", class: 'profile-image' %>
          <div class='profile-name'>
            <%= @item.user.nickname %>
          </div>

          <div class='profile-message'>
            <i class="fa fa-envelope"></i>メッセージで意見や質問を送る
          </div>
        </div>
      </div>

      <div class='return-detail'>
        <h2>リターンを選ぶ</h2>
        <ul>
          <li class='return-list'>
            <div class='return-list-box'>
              <div class='return-money'>
                500円
              </div>
              <div class='btn-return'>
                <% if user_signed_in? && current_user.id == @item.user_id %>
                  <%= link_to 'このリターンを選択する', class:'return-link' %>
                <% elsif @item.remaining_days > 0 %>
                  <%= link_to 'このリターンを選択する', new_item_order_path(@item.id), class:'return-link' %>
                <% else %>
                  <%= link_to 'このリターンを選択する', class:'return-link' %>
                <% end %>
              </div>
              <div class='return-message'>
                <p>
                お礼メッセージ<br/>
                ご支援いただいた方に、心からのお礼をお送りさせていただきます。
                </p>
                <p class='remarks_field'>
                  ※支援時、必ず備考欄にご希望のお名前をご記入ください。
                </p>
              </div>
              <div class='support-person-list'>
                <div class='person-list-number'>支援者：<%= @item.person_num %>人</div>
                <div class='delivery_scheduled'>お届け予定：2020年12月</div>
              </div>

            </div>
          </li>
          <li class='return-list'>
            <div class='return-list-box'>
              <div class='return-money'>
                8000円
              </div>
              <div class='btn-return'>
                <% if user_signed_in? && current_user.id == @item.user_id %>
                  <%= link_to 'このリターンを選択する', class:'return-link' %>
                <% elsif @item.remaining_days > 0 %>
                  <%= link_to 'このリターンを選択する', new_item_order_path(@item.id), class:'return-link' %>
                <% else %>
                  <%= link_to 'このリターンを選択する', class:'return-link' %>
                <% end %>
              </div>
              <div class='return-message'>
                <p>
                お礼メッセージ<br/>
                ご支援いただいた方に、心からのお礼をお送りさせていただきます。
                </p>
                <p class='remarks_field'>
                  ※支援時、必ず備考欄にご希望のお名前をご記入ください。
                </p>
              </div>
              <div class='support-person-list'>
                <div class='person-list-number'>支援者：<%= @item.person_num %>人</div>
                <div class='delivery_scheduled'>お届け予定：2020年12月</div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<%= render "items/footer" %>